{{- if and .Values.auth.rotatePassword .Values.auth.enabled .Values.auth.resolver }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  resolver.conf: |-
    accounts: {
      "$SYS": {
        users: [
          {
            user: "admin",
            password: "{{ include "getAdminPassword" (dict "pass" .Values.auth.adminPassword) }}"
          }
        ]
      },
    }
    system_account: "$SYS"
{{- end }}
