---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- if or .Values.serviceAnnotations .Values.commonAnnotations}}
  annotations:
  {{- if .Values.serviceAnnotations }}
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  {{- if .Values.nats.profiling.enabled }}
  - name: profiling
    port: {{ .Values.nats.profiling.port }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  {{- end }}
  - name: client
    port: {{ .Values.nats.ports.client }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  - name: cluster
    port: {{ .Values.nats.ports.cluster }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  - name: monitor
    port: {{ .Values.nats.ports.monitoring }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  - name: metrics
    port: {{ .Values.nats.ports.metrics }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  - name: leafnodes
    port: {{ .Values.nats.ports.leafnodes }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  - name: gateways
    port: {{ .Values.nats.ports.gateways }}
    protocol: TCP
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
