---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nats.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- if or .Values.statefulSetAnnotations .Values.commonAnnotations}}
  annotations:
  {{- if .Values.statefulSetAnnotations }}
    {{- toYaml .Values.statefulSetAnnotations | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nats.selectorLabels" . | nindent 6 }}
  {{- if .Values.cluster.enabled }}
  replicas: {{ .Values.cluster.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  serviceName: {{ include "nats.fullname" . }}

  podManagementPolicy: {{ .Values.global.jetstream.podManagementPolicy }}

  template:
    metadata:
      {{- if or .Values.exporter.enabled .Values.nats.configChecksumAnnotation .Values.podAnnotations }}
      annotations:
      {{- if .Values.exporter.enabled }}
        prometheus.io/scrape: "false"
      {{- end }}
      {{- if .Values.nats.configChecksumAnnotation }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
        {{- toYaml .Values.commonAnnotations | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "nats.selectorLabels" . | nindent 8 }}
        {{- if .Values.statefulSetPodLabels }}
        {{ toYaml .Values.statefulSetPodLabels | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{ toYaml .Values.commonLabels | nindent 8 }}
        {{- end }}
    spec:
{{- if or .Values.priorityClassName .Values.global.priorityClassName }}
      priorityClassName: {{ coalesce .Values.priorityClassName .Values.global.priorityClassName }}
{{- end }}
{{- if .Values.podSecurityContext }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- tpl (toYaml .) $ | nindent 8 }}
{{- end }}
      # Common volumes for the containers.
      volumes:
      ### the secret that holds account data ###
      {{- if and .Values.auth.enabled .Values.auth.resolver }}
      - name: accounts-volume
        secret:
          secretName: {{ include "nats.fullname" . }}-secret
      {{- end }}
      - name: config-volume
        configMap:
          name: {{ include "nats.fullname" . }}-config

      # Local volume shared with the reloader.
      - name: pid
        emptyDir: {}

      {{- if and (eq .Values.global.jetstream.storage "file") .Values.nats.jetstream.fileStorage.existingClaim }}
      # Persistent volume for jetstream running with file storage option
      - name: {{ include "nats.fullname" . }}-js-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.nats.jetstream.fileStorage.existingClaim | quote }}
      {{- end }}

      # Required to be able to HUP signal and apply config
      # reload to the server without restarting the pod.
      shareProcessNamespace: true

      #################
      #               #
      #  NATS Server  #
      #               #
      #################
      terminationGracePeriodSeconds: {{ .Values.nats.terminationGracePeriodSeconds }}
      containers:
      #################################
      #                               #
      #  NATS Configuration Reloader  #
      #                               #
      #################################
      - name: config-reloader
        image: "{{ include "imageurl" (dict "reg" .Values.global.containerRegistry "img" .Values.global.images.nats_config_reloader) }}"
        imagePullPolicy: {{ .Values.nats.pullPolicy }}
        {{- if .Values.containerSecurityContext }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        command:
          - "nats-server-config-reloader"
          - "-pid"
          - "/var/run/nats/nats.pid"
          - "-config"
          - "/etc/nats-config/nats.conf"
          - "-config"
          - "/etc/nats-config/accounts/resolver.conf"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nats-config
          - name: pid
            mountPath: /var/run/nats
          - name: accounts-volume
            mountPath: /etc/nats-config/accounts

      ##############################
      #                            #
      #  NATS Prometheus Exporter  #
      #                            #
      ##############################
      {{- if .Values.exporter.enabled }}
      - name: metrics
        image: "{{ include "imageurl" (dict "reg" .Values.global.containerRegistry "img" .Values.global.images.prometheus_nats_exporter) }}"
        imagePullPolicy: {{ .Values.exporter.pullPolicy }}
        {{- if .Values.containerSecurityContext }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.exporter.resources | nindent 10 }}
        args:
        - -connz
        - -routez
        - -subz
        - -varz
        - -healthz
        - -prefix=nats
        - -use_internal_server_id
        - -jsz=all
        - http://localhost:8222/
        ports:
          - containerPort: 7777
            name: metrics
            protocol: TCP
      {{- end }}
      - name: nats
        image: "{{ include "imageurl" (dict "reg" .Values.global.containerRegistry "img" .Values.global.images.nats) }}"
        imagePullPolicy: {{ .Values.nats.pullPolicy }}
        {{- if .Values.containerSecurityContext }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.nats.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.nats.ports.client }}
          name: client
          protocol: TCP
        - containerPort: {{ .Values.nats.ports.leafnodes }}
          name: leafnodes
          protocol: TCP
        - containerPort: {{ .Values.nats.ports.gateways }}
          name: gateways
          protocol: TCP
        - containerPort: {{ .Values.nats.ports.cluster }}
          name: cluster
          protocol: TCP
        - containerPort: {{ .Values.nats.ports.monitoring }}
          name: monitor
          protocol: TCP
        - containerPort: {{ .Values.nats.ports.metrics }}
          name: metrics
          protocol: TCP
        {{- if .Values.nats.profiling.enabled }}
        - containerPort: {{ .Values.nats.profiling.port }}
          name: profiling
          protocol: TCP
        {{- end }}

        command:
         - "nats-server"
         - "--config"
         - "/etc/nats-config/nats.conf"
        {{- if .Values.nats.profiling.enabled }}
         - "--profile={{ .Values.nats.profiling.port }}"
        {{- end }}

        # Required to be able to define an environment variable
        # that refers to other environment variables.  This env var
        # is later used as part of the configuration file.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: {{ include "nats.clusterAdvertise" . }}

        {{- with .Values.nats.jetstream.encryption }}
        {{- with .secret }}
        - name: JS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .key }}
        {{- end }}
        {{- end }}
        volumeMounts:
          ### the secret that holds account data ###
          {{- if and .Values.auth.enabled .Values.auth.resolver }}
          {{- if eq .Values.auth.resolver.type "memory" }}
          - name: accounts-volume
            mountPath: /etc/nats-config/accounts
          {{- end }}
          {{- end }}
          - name: config-volume
            mountPath: /etc/nats-config
          - name: pid
            mountPath: /var/run/nats
          {{- if (eq .Values.global.jetstream.storage "file") }}
          - name: {{ include "nats.fullname" . }}-js-pvc
            mountPath: {{ .Values.nats.jetstream.fileStorage.storageDirectory }}
          {{- end }}

        #######################
        #                     #
        # Healthcheck Probes  #
        #                     #
        #######################
        {{- if .Values.nats.healthcheck }}

        {{- with .Values.nats.healthcheck.liveness }}
        {{- if .enabled }}
        livenessProbe:
          httpGet:
            path: {{ .endpoint }}
            port: 8222
          initialDelaySeconds: {{ .initialDelaySeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- if .terminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
          {{- end }}
        {{- end }}
        {{- end }}

        {{- with .Values.nats.healthcheck.readiness }}
        {{- if .enabled }}
        readinessProbe:
          httpGet:
            path: {{ .endpoint }}
            port: 8222
          initialDelaySeconds: {{ .initialDelaySeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- end }}

        {{- with .Values.nats.healthcheck.startup }}
        {{- if .enabled }}
        startupProbe:
          httpGet:
            path: {{ .endpoint }}
            port: 8222
          initialDelaySeconds: {{ .initialDelaySeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- end }}

        {{- end }}

        # Gracefully stop NATS Server on pod deletion or image upgrade.
        #
        lifecycle:
          preStop:
            exec:
              # send the lame duck shutdown signal to trigger a graceful shutdown
              # nats-server will ignore the TERM signal it receives after this
              #
              command:
              - "nats-server"
              - "-sl=ldm=/var/run/nats/nats.pid"

  volumeClaimTemplates:
  {{- if and (eq .Values.global.jetstream.storage "file") (not .Values.nats.jetstream.fileStorage.existingClaim) }}
  #####################################
  #                                   #
  #  Jetstream New Persistent Volume  #
  #                                   #
  #####################################
    - metadata:
        name: {{ include "nats.fullname" . }}-js-pvc
        {{- if .Values.nats.jetstream.fileStorage.annotations }}
        annotations:
          {{- toYaml .Values.nats.jetstream.fileStorage.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.nats.jetstream.fileStorage.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.global.jetstream.fileStorage.size }}
        {{- if and (.Values.nats.jetstream.fileStorage.storageClassName) (ne .Values.nats.jetstream.fileStorage.storageClassName "default") }}
        storageClassName: {{ .Values.nats.jetstream.fileStorage.storageClassName | quote }}
        {{- end }}
  {{- end }}
