version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - depguard
    - dupl
    - errchkjson
    - exhaustruct
    - forcetypeassert
    - gosec
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - sqlclosecheck
    - tagliatelle
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - varnamelen
    - wrapcheck
    - wsl
    # TODO re-enable:
    - err113
    - funcorder
    - staticcheck
    - usetesting
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 100
    gomoddirectives:
      replace-allow-list:
        - github.com/prometheus/client_golang
    importas:
      alias:
        - pkg: log
          alias: log
        - pkg: k8s.io/api/core/v1
          alias: kcorev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: kmetav1
        - pkg: k8s.io/client-go/dynamic/fake
          alias: kdynamicfake
        - pkg: github.com/nats-io/nats.go
          alias: natsgo
        - pkg: go.opencensus.io/trace/propagation
          alias: ocpropagation
        - pkg: github.com/kyma-project/eventing-publisher-proxy/testing
          alias: epptestingutils
        - pkg: github.com/kyma-project/eventing-publisher-proxy/pkg/legacy/api
          alias: eppapi
        - pkg: github.com/kyma-project/eventing-publisher-proxy/pkg/nats
          alias: eppnats
        - pkg: github.com/kyma-project/eventing-manager/pkg/logger
          alias: emlogger
        - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha1
          alias: emeventingv1alpha1
        - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha2
          alias: emeventingv2alpha1
        - pkg: github.com/cloudevents/sdk-go/v2
          alias: ce
        - pkg: github.com/cloudevents/sdk-go/v2/protocol/http
          alias: cehttp
        - pkg: github.com/cloudevents/sdk-go/v2/event
          alias: ceevent
        - pkg: github.com/cloudevents/sdk-go/v2/client
          alias: ceclient
        - pkg: github.com/kyma-project/kyma/components/central-application-gateway/pkg/apis/applicationconnector/v1alpha1
          alias: kymaappconnv1alpha1
        - pkg: github.com/kyma-project/eventing-auth-manager/internal/ias
          alias: eamias
        - pkg: github.com/kyma-project/eventing-auth-manager/controllers
          alias: eamcontrollers
        - pkg: github.com/kyma-project/eventing-auth-manager/api/v1alpha1
          alias: eamapiv1alpha1
        - pkg: github.com/kyma-project/eventing-auth-manager/internal/ias/internal/oidc/mocks
          alias: eamoidcmocks
        - pkg: github.com/kyma-project/lifecycle-manager/api/v1beta1
          alias: klmapiv1beta1
        - pkg: github.com/kyma-project/lifecycle-manager/api/v1beta2
          alias: klmapiv1beta2
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: kapierrors
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: kpkgclient
        - pkg: k8s.io/apimachinery/pkg/util/runtime
          alias: kutilruntime
        - pkg: k8s.io/client-go/kubernetes/scheme
          alias: kscheme
        - pkg: sigs.k8s.io/controller-runtime
          alias: kcontrollerruntime
        - pkg: sigs.k8s.io/controller-runtime/pkg/reconcile
          alias: kcontrollerruntimereconcile
        - pkg: github.com/onsi/gomega/types
          alias: onsigomegatypes
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: kpkglog
        - pkg: k8s.io/api/apps/v1
          alias: kappsv1
        - pkg: k8s.io/apimachinery/pkg/types
          alias: ktypes
        - pkg: sigs.k8s.io/controller-runtime/pkg/log/zap
          alias: klogzap
        - pkg: github.com/kyma-project/nats-manager/pkg/k8s/mocks
          alias: nmkmocks
        - pkg: github.com/kyma-project/nats-manager/pkg/nats/mocks
          alias: nmnatsmocks
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: kapiextv1
        - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
          alias: kapiextclientset
        - pkg: github.com/kyma-project/nats-manager/internal/controller/nats
          alias: nmctrl
        - pkg: github.com/kyma-project/nats-manager/api/v1alpha1
          alias: nmapiv1alpha1
        - pkg: k8s.io/api/policy/v1
          alias: kapipolicyv1
        - pkg: github.com/kyma-project/nats-manager/pkg/k8s/chart/mocks
          alias: nmkchartmocks
        - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake
          alias: kapiextclientsetfake
        - pkg: k8s.io/apimachinery/pkg/util/yaml
          alias: kutilyaml
        - pkg: github.com/kyma-project/nats-manager/pkg/manager/mocks
          alias: nmmgrmocks
        - pkg: github.com/kyma-project/nats-manager/internal/controller/nats/mocks
          alias: nmctrlmocks
        - pkg: github.com/kyma-project/nats-manager/pkg/manager
          alias: nmmgr
        - pkg: github.com/kyma-project/nats-manager/internal/controller/nats/url
          alias: nmctrlurl
        - pkg: github.com/kyma-project/nats-manager/testutils/matchers/nats
          alias: nmtsmatchers
        - pkg: k8s.io/api/events/v1
          alias: keventsv1
        - pkg: github.com/kyma-project/nats-manager/pkg/nats
          alias: nmnats
        - pkg: k8s.io/api/rbac/v1
          alias: krbacv1
        - pkg: k8s.io/api/autoscaling/v1
          alias: kautoscalingv1
        - pkg: github.com/kyma-project/nats-manager/internal/controller/cache
          alias: nmctrlcache
        - pkg: github.com/kyma-project/nats-manager/pkg/labels
          alias: nmlabels
        - pkg: github.com/prometheus/client_golang/prometheus/testutil
          alias: ptestutil
      no-unaliased: false
      no-extra-aliases: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - Client
        - client.Object
        - (or|er)$
    nestif:
      min-complexity: 6
    revive:
      severity: error
      enable-all-rules: false
      rules:
        - name: comment-spacings
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - maintidx
          - wrapcheck
        path: _test\.go
      - linters:
          - importas
        text: has alias "" which is not part of config
    paths:
      - zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kyma-project/eventing-manager)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
