linters:
  enable-all: true
  disable:
    - contextcheck # too many false positives
    - deadcode # deprecated (since v1.49.0) and replaced by 'unused'
    - depguard # checks if package imports are whitelisted
    - exhaustivestruct # deprecated (since v1.46.0) and replaced by 'exhaustruct'
    - exhaustruct # TODO enable and fix, use regex to exclude certain cases
    - golint # deprecated (since v1.41.0) and replaced by 'revive'
    - ifshort # deprecated (since v1.48.0)
    - interfacer # deprecated (since v1.38.0)
    - lll
    - maligned # deprecated (since v1.38.0)
    - nlreturn # too strict and mostly code is not more readable
    - nosnakecase # deprecated (since v1.48.1) and replaced by 'revive'
    - scopelint # deprecated (since v1.39.0) and replaced by 'exportloopref'
    - structcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - sqlclosecheck # not needed for this project
    - varcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - wsl # too strict and mostly code is not more readable
    - dupl
    - forcetypeassert
    - gosec
    - inamedparam
    - ireturn
    - maintidx
    - nolintlint
    - paralleltest
    - prealloc
    - testpackage
    - tparallel
    - unconvert
    - varnamelen
    - wrapcheck
    - gci
    - tagalign
    - dupword
    - gomoddirectives
    - funlen
    - testifylint
    - bodyclose
    - containedctx
    - thelper
    - tagliatelle
    - errchkjson
    - perfsprint
    - noctx

linters-settings:
  gomoddirectives:
    replace-allow-list:
      - github.com/prometheus/client_golang
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
  revive:
    enable-all-rules: false
    severity: error
    rules:
      - name: comment-spacings
        disabled: true
      - name: dot-imports
        severity: warning
        disabled: true
      - name: line-length-limit
        severity: warning
        disabled: true
        arguments: [120]
  funlen:
    lines: 100
  cyclop:
    max-complexity: 20
  nestif:
    min-complexity: 6
  gci:
    sections:
      - standard # Standard packages.
      - default # Imports that could not be matched to another section type.
      - prefix(github.com/kyma-project/eventing-manager) # Imports with the specified prefix.
      - blank # Blank imports.
      - dot # Dot imports.
    custom-order: true
    skip-generated: true
  importas:
    no-unaliased: false
    no-extra-aliases: true
    ## Version number must be added as suffix to the package name. As an example check `k8s.io/api/core/v1`
    ## kubernetes APIs get the prefix `k`. As an example check `kcorev1`
    ## Eventing Manager APIs get the prefix `em`. As an example check `emeventingv1alpha1`
    ## Eventing Publisher Proxy APIs get the prefix `epp`. As an example check `eppapi`
    ## Cloud Events APIs get the prefix `ce`. As an example check `ce`
    ## Eventing Auth Manager APIs get the prefix `eam`.
    ## Kyma Metrics Collector APIs get the prefix `kmc`.
    ## NATS Manager APIs get the prefix `nm`.

    alias:
      - pkg: "log"
        alias: log
      - pkg: k8s.io/api/core/v1
        alias: kcorev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: kmetav1
      - pkg: k8s.io/client-go/dynamic/fake
        alias: kdynamicfake
      - pkg: github.com/nats-io/nats.go
        alias: natsgo
      - pkg: go.opencensus.io/trace/propagation
        alias: ocpropagation
      - pkg: github.com/kyma-project/eventing-publisher-proxy/testing
        alias: epptestingutils
      - pkg: github.com/kyma-project/eventing-publisher-proxy/pkg/legacy/api
        alias: eppapi
      - pkg: github.com/kyma-project/eventing-publisher-proxy/pkg/nats
        alias: eppnats
      - pkg: github.com/kyma-project/eventing-manager/pkg/logger
        alias: emlogger
      - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha1
        alias: emeventingv1alpha1
      - pkg: github.com/kyma-project/eventing-manager/api/eventing/v1alpha2
        alias: emeventingv2alpha1
      - pkg: github.com/cloudevents/sdk-go/v2
        alias: ce
      - pkg: github.com/cloudevents/sdk-go/v2/protocol/http
        alias: cehttp
      - pkg: github.com/cloudevents/sdk-go/v2/event
        alias: ceevent
      - pkg: github.com/cloudevents/sdk-go/v2/client
        alias: ceclient
      - pkg: github.com/kyma-project/kyma/components/central-application-gateway/pkg/apis/applicationconnector/v1alpha1
        alias: kymaappconnv1alpha1

        ######
        ### The following imports are used by github.com/kyma-project/eventing-auth-manager repository.
        ######
      - pkg: github.com/kyma-project/eventing-auth-manager/internal/ias
        alias: eamias
      - pkg: github.com/kyma-project/eventing-auth-manager/controllers
        alias: eamcontrollers
      - pkg: github.com/kyma-project/eventing-auth-manager/api/v1alpha1
        alias: eamapiv1alpha1
      - pkg: github.com/kyma-project/eventing-auth-manager/internal/ias/internal/oidc/mocks
        alias: eamoidcmocks
      - pkg: github.com/kyma-project/lifecycle-manager/api/v1beta1
        alias: klmapiv1beta1
      - pkg: github.com/kyma-project/lifecycle-manager/api/v1beta2
        alias: klmapiv1beta2
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: kapierrors
      - pkg: sigs.k8s.io/controller-runtime/pkg/client
        alias: kpkgclient
      - pkg: k8s.io/apimachinery/pkg/util/runtime
        alias: kutilruntime
      - pkg: k8s.io/client-go/kubernetes/scheme
        alias: kscheme
      - pkg: sigs.k8s.io/controller-runtime
        alias: kcontrollerruntime
      - pkg: github.com/onsi/gomega/types
        alias: onsigomegatypes
      - pkg: sigs.k8s.io/controller-runtime/pkg/log
        alias: kpkglog

        ######
        ### The following imports are used by github.com/kyma-project/nats-manager repository.
        ######
      - pkg: k8s.io/api/apps/v1
        alias: kappsv1
      - pkg: k8s.io/apimachinery/pkg/types
        alias: ktypes
      - pkg: sigs.k8s.io/controller-runtime/pkg/log/zap
        alias: klogzap
      - pkg: github.com/kyma-project/nats-manager/pkg/k8s/mocks
        alias: nmkmocks
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: kapiextv1
      - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
        alias: kapiextclientset
      - pkg: github.com/kyma-project/nats-manager/internal/controller/nats
        alias: nmctrl
      - pkg: github.com/kyma-project/nats-manager/api/v1alpha1
        alias: nmapiv1alpha1
      - pkg: k8s.io/api/policy/v1
        alias: kapipolicyv1
      - pkg: github.com/kyma-project/nats-manager/pkg/k8s/chart/mocks
        alias: nmkchartmocks
      - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake
        alias: kapiextclientsetfake
      - pkg: k8s.io/apimachinery/pkg/util/yaml
        alias: kutilyaml
      - pkg: github.com/kyma-project/nats-manager/pkg/manager/mocks
        alias: nmmgrmocks
      - pkg: github.com/kyma-project/nats-manager/internal/controller/nats/mocks
        alias: nmctrlmocks
      - pkg: github.com/kyma-project/nats-manager/pkg/manager
        alias: nmmgr
      - pkg: github.com/kyma-project/nats-manager/internal/controller/nats/url
        alias: nmctrlurl
      - pkg: github.com/kyma-project/nats-manager/testutils/matchers/nats
        alias: nmtsmatchers
      - pkg: k8s.io/api/events/v1
        alias: keventsv1
      - pkg: github.com/kyma-project/nats-manager/pkg/nats
        alias: nmnats
      - pkg: k8s.io/api/rbac/v1
        alias: krbacv1
      - pkg: k8s.io/api/autoscaling/v1
        alias: kautoscalingv1
      - pkg: github.com/kyma-project/nats-manager/internal/controller/cache
        alias: nmctrlcache
      - pkg: github.com/kyma-project/nats-manager/pkg/labels
        alias: nmlabels

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - Client
      - client.Object
      - (or|er)$
  wrapcheck:
    ignorePackageGlobs:
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - wrapcheck
        - gochecknoglobals
        - funlen # Table driven unit and integration tests exceed function length by design
        - maintidx # Table driven unit and integration tests exceed maintainability index by design
    - linters:
        - importas
      text: has alias "" which is not part of config # Ignore false positives that emerged due to https://github.com/julz/importas/issues/15.
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  sort-results: true
run:
  timeout: 15m
  skip-files:
    - zz_generated.deepcopy.go
