module-name: nats
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/nats-manager:main
  - europe-docker.pkg.dev/kyma-project/prod/external/natsio/prometheus-nats-exporter:0.19.2
  - europe-docker.pkg.dev/kyma-project/prod/external/natsio/nats-server-config-reloader:0.22.3
  - europe-docker.pkg.dev/kyma-project/prod/external/library/nats:2.12.6-alpine3.22
  - europe-docker.pkg.dev/kyma-project/prod/external/library/alpine:3.22
  - europe-docker.pkg.dev/kyma-project/restricted-prod/nats-fips:2.12.600
  - europe-docker.pkg.dev/kyma-project/restricted-prod/nats-server-config-reloader-fips:0.22.300
  - europe-docker.pkg.dev/kyma-project/restricted-prod/prometheus-nats-exporter-fips:0.19.200
  - europe-docker.pkg.dev/kyma-project/restricted-prod/bash-fips:5.301
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
