# Adds namespace to all resources.
namespace: kyma-system

# Labels to add to all resources and selectors.
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: nats-manager
      app.kubernetes.io/created-by: nats-manager
      app.kubernetes.io/instance: nats-manager
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: nats-manager
      app.kubernetes.io/part-of: Kyma
      control-plane: nats-manager
      kyma-project.io/module: nats

resources:
- ../customer_rbac
