// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	natsgo "github.com/nats-io/nats.go"
)

// NatsConn is an autogenerated mock type for the NatsConn type
type NatsConn struct {
	mock.Mock
}

type NatsConn_Expecter struct {
	mock *mock.Mock
}

func (_m *NatsConn) EXPECT() *NatsConn_Expecter {
	return &NatsConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *NatsConn) Close() {
	_m.Called()
}

// NatsConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type NatsConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *NatsConn_Expecter) Close() *NatsConn_Close_Call {
	return &NatsConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *NatsConn_Close_Call) Run(run func()) *NatsConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NatsConn_Close_Call) Return() *NatsConn_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *NatsConn_Close_Call) RunAndReturn(run func()) *NatsConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with given fields:
func (_m *NatsConn) IsConnected() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NatsConn_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type NatsConn_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *NatsConn_Expecter) IsConnected() *NatsConn_IsConnected_Call {
	return &NatsConn_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *NatsConn_IsConnected_Call) Run(run func()) *NatsConn_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NatsConn_IsConnected_Call) Return(_a0 bool) *NatsConn_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsConn_IsConnected_Call) RunAndReturn(run func() bool) *NatsConn_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// JetStream provides a mock function with given fields:
func (_m *NatsConn) JetStream() (natsgo.JetStreamContext, error) {
	ret := _m.Called()

	var r0 natsgo.JetStreamContext
	var r1 error
	if rf, ok := ret.Get(0).(func() (natsgo.JetStreamContext, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() natsgo.JetStreamContext); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(natsgo.JetStreamContext)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NatsConn_JetStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JetStream'
type NatsConn_JetStream_Call struct {
	*mock.Call
}

// JetStream is a helper method to define mock.On call
func (_e *NatsConn_Expecter) JetStream() *NatsConn_JetStream_Call {
	return &NatsConn_JetStream_Call{Call: _e.mock.On("JetStream")}
}

func (_c *NatsConn_JetStream_Call) Run(run func()) *NatsConn_JetStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NatsConn_JetStream_Call) Return(_a0 natsgo.JetStreamContext, _a1 error) *NatsConn_JetStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NatsConn_JetStream_Call) RunAndReturn(run func() (natsgo.JetStreamContext, error)) *NatsConn_JetStream_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields:
func (_m *NatsConn) Status() natsgo.Status {
	ret := _m.Called()

	var r0 natsgo.Status
	if rf, ok := ret.Get(0).(func() natsgo.Status); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(natsgo.Status)
	}

	return r0
}

// NatsConn_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type NatsConn_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *NatsConn_Expecter) Status() *NatsConn_Status_Call {
	return &NatsConn_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *NatsConn_Status_Call) Run(run func()) *NatsConn_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NatsConn_Status_Call) Return(_a0 natsgo.Status) *NatsConn_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NatsConn_Status_Call) RunAndReturn(run func() natsgo.Status) *NatsConn_Status_Call {
	_c.Call.Return(run)
	return _c
}

// NewNatsConn creates a new instance of NatsConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNatsConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *NatsConn {
	mock := &NatsConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
