// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	logr "github.com/go-logr/logr"

	mock "github.com/stretchr/testify/mock"

	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"

	source "sigs.k8s.io/controller-runtime/pkg/source"
)

// TypedController is an autogenerated mock type for the TypedController type
type TypedController[request comparable] struct {
	mock.Mock
}

type TypedController_Expecter[request comparable] struct {
	mock *mock.Mock
}

func (_m *TypedController[request]) EXPECT() *TypedController_Expecter[request] {
	return &TypedController_Expecter[request]{mock: &_m.Mock}
}

// GetLogger provides a mock function with no fields
func (_m *TypedController[request]) GetLogger() logr.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logr.Logger
	if rf, ok := ret.Get(0).(func() logr.Logger); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(logr.Logger)
	}

	return r0
}

// TypedController_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type TypedController_GetLogger_Call[request comparable] struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *TypedController_Expecter[request]) GetLogger() *TypedController_GetLogger_Call[request] {
	return &TypedController_GetLogger_Call[request]{Call: _e.mock.On("GetLogger")}
}

func (_c *TypedController_GetLogger_Call[request]) Run(run func()) *TypedController_GetLogger_Call[request] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TypedController_GetLogger_Call[request]) Return(_a0 logr.Logger) *TypedController_GetLogger_Call[request] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TypedController_GetLogger_Call[request]) RunAndReturn(run func() logr.Logger) *TypedController_GetLogger_Call[request] {
	_c.Call.Return(run)
	return _c
}

// Reconcile provides a mock function with given fields: _a0, _a1
func (_m *TypedController[request]) Reconcile(_a0 context.Context, _a1 request) (reconcile.Result, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 reconcile.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request) (reconcile.Result, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request) reconcile.Result); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TypedController_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type TypedController_Reconcile_Call[request comparable] struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 request
func (_e *TypedController_Expecter[request]) Reconcile(_a0 interface{}, _a1 interface{}) *TypedController_Reconcile_Call[request] {
	return &TypedController_Reconcile_Call[request]{Call: _e.mock.On("Reconcile", _a0, _a1)}
}

func (_c *TypedController_Reconcile_Call[request]) Run(run func(_a0 context.Context, _a1 request)) *TypedController_Reconcile_Call[request] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request))
	})
	return _c
}

func (_c *TypedController_Reconcile_Call[request]) Return(_a0 reconcile.Result, _a1 error) *TypedController_Reconcile_Call[request] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TypedController_Reconcile_Call[request]) RunAndReturn(run func(context.Context, request) (reconcile.Result, error)) *TypedController_Reconcile_Call[request] {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *TypedController[request]) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TypedController_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type TypedController_Start_Call[request comparable] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TypedController_Expecter[request]) Start(ctx interface{}) *TypedController_Start_Call[request] {
	return &TypedController_Start_Call[request]{Call: _e.mock.On("Start", ctx)}
}

func (_c *TypedController_Start_Call[request]) Run(run func(ctx context.Context)) *TypedController_Start_Call[request] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TypedController_Start_Call[request]) Return(_a0 error) *TypedController_Start_Call[request] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TypedController_Start_Call[request]) RunAndReturn(run func(context.Context) error) *TypedController_Start_Call[request] {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: src
func (_m *TypedController[request]) Watch(src source.TypedSource[request]) error {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(source.TypedSource[request]) error); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TypedController_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type TypedController_Watch_Call[request comparable] struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - src source.TypedSource[request]
func (_e *TypedController_Expecter[request]) Watch(src interface{}) *TypedController_Watch_Call[request] {
	return &TypedController_Watch_Call[request]{Call: _e.mock.On("Watch", src)}
}

func (_c *TypedController_Watch_Call[request]) Run(run func(src source.TypedSource[request])) *TypedController_Watch_Call[request] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(source.TypedSource[request]))
	})
	return _c
}

func (_c *TypedController_Watch_Call[request]) Return(_a0 error) *TypedController_Watch_Call[request] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TypedController_Watch_Call[request]) RunAndReturn(run func(source.TypedSource[request]) error) *TypedController_Watch_Call[request] {
	_c.Call.Return(run)
	return _c
}

// NewTypedController creates a new instance of TypedController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTypedController[request comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *TypedController[request] {
	mock := &TypedController[request]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
