# default.yaml is passed to kyma alpha create module command.
apiVersion: operator.kyma-project.io/v1alpha1
kind: NATS
metadata:
  name: eventing-nats
  namespace: kyma-system
spec:
  cluster:
    size: 3
  jetStream:
    fileStorage:
      size: "1Gi"
      storageClassName: "default"
    memStorage:
      enabled: true
      size: "1Gi"
  logging:
    debug: false
    trace: false
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 40m
      memory: 64Mi
