apiVersion: v1
kind: Namespace
metadata:
  name: kyma-system
---
apiVersion: operator.kyma-project.io/v1alpha1
kind: NATS
metadata:
  name: eventing-nats
  namespace: kyma-system
spec:
  cluster:
    size: 3
