apiVersion: operator.kyma-project.io/v1alpha1
kind: NATS
metadata:
  name: eventing-nats
  namespace: kyma-system
spec:
  cluster:
    size: 3
  jetStream:
    memStorage: 
      enabled: true 
      size: 512Mi
    fileStorage:
      storageClassName: default 
      size: 512Mi
