// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	nats_go "github.com/nats-io/nats.go"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *Client) Close() {
	_m.Called()
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return() *Client_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func()) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumersExist provides a mock function with given fields: streamName
func (_m *Client) ConsumersExist(streamName string) (bool, error) {
	ret := _m.Called(streamName)

	if len(ret) == 0 {
		panic("no return value specified for ConsumersExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(streamName)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(streamName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(streamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ConsumersExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumersExist'
type Client_ConsumersExist_Call struct {
	*mock.Call
}

// ConsumersExist is a helper method to define mock.On call
//   - streamName string
func (_e *Client_Expecter) ConsumersExist(streamName interface{}) *Client_ConsumersExist_Call {
	return &Client_ConsumersExist_Call{Call: _e.mock.On("ConsumersExist", streamName)}
}

func (_c *Client_ConsumersExist_Call) Run(run func(streamName string)) *Client_ConsumersExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_ConsumersExist_Call) Return(_a0 bool, _a1 error) *Client_ConsumersExist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ConsumersExist_Call) RunAndReturn(run func(string) (bool, error)) *Client_ConsumersExist_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreams provides a mock function with given fields:
func (_m *Client) GetStreams() ([]*nats_go.StreamInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStreams")
	}

	var r0 []*nats_go.StreamInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*nats_go.StreamInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*nats_go.StreamInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*nats_go.StreamInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreams'
type Client_GetStreams_Call struct {
	*mock.Call
}

// GetStreams is a helper method to define mock.On call
func (_e *Client_Expecter) GetStreams() *Client_GetStreams_Call {
	return &Client_GetStreams_Call{Call: _e.mock.On("GetStreams")}
}

func (_c *Client_GetStreams_Call) Run(run func()) *Client_GetStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetStreams_Call) Return(_a0 []*nats_go.StreamInfo, _a1 error) *Client_GetStreams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetStreams_Call) RunAndReturn(run func() ([]*nats_go.StreamInfo, error)) *Client_GetStreams_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields:
func (_m *Client) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type Client_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *Client_Expecter) Init() *Client_Init_Call {
	return &Client_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *Client_Init_Call) Run(run func()) *Client_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Init_Call) Return(_a0 error) *Client_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Init_Call) RunAndReturn(run func() error) *Client_Init_Call {
	_c.Call.Return(run)
	return _c
}

// StreamExists provides a mock function with given fields:
func (_m *Client) StreamExists() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StreamExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_StreamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamExists'
type Client_StreamExists_Call struct {
	*mock.Call
}

// StreamExists is a helper method to define mock.On call
func (_e *Client_Expecter) StreamExists() *Client_StreamExists_Call {
	return &Client_StreamExists_Call{Call: _e.mock.On("StreamExists")}
}

func (_c *Client_StreamExists_Call) Run(run func()) *Client_StreamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_StreamExists_Call) Return(_a0 bool, _a1 error) *Client_StreamExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_StreamExists_Call) RunAndReturn(run func() (bool, error)) *Client_StreamExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
