name: Pull Build Image

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: nats-manager
      dockerfile: Dockerfile
      context: .
      export-tags: true
