name: Tag Build Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # This will trigger the workflow when a tag (x.y.z) is pushed.

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tag.outputs.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: |
          {
            echo 'TAGS<<EOF'
            echo "${{ github.sha }}"
            echo "${{ github.ref_name}}"
            echo EOF
          } >> "$GITHUB_OUTPUT"
  build:
    name: build-${{ github.ref_name }} # The release pipeline will check the status of this job by this name format (e.g. build-1.0.1).
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: nats-manager
      dockerfile: Dockerfile
      context: .
      tags: ${{ needs.compute-tags.outputs.tags }}
