name: validate crd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.26.5
      - name: apply crd
        run: kubectl apply -f config/crd/bases/operator.kyma-project.io_nats.yaml